### PR TITLE
Corrected default value of Ensure in help

### PR DESCRIPTION
**Pull request by ITGuyOU**
For xScheduledTask

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/66)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @ITGuyOU - the tests seem to be failing on this one. Are you able to resolve this? One thing to note: the change may be affected by this PR that is scheduled to go in: https://github.com/PowerShell/xComputerManagement/pull/69

**Comment by ITGuyOU** [comment]
Hey @PlagueHO . Is the documentation change I made causing the tests to fail? Or are you asking if I can take a look at some of the issues plaguing the PSScriptAnalyzer?

**Comment by PlagueHO** [comment]
Hi @ITGuyOU - actually, I took a look at the tests that failed, and I think they may have actually been caused by a change to Pester. I think the Pester team have actually fixed the issue.

So are you able to trigger a dummy commit to force AppVeyor to run again? E.g. just make some trivial change to the README.MD or something and push it - this will tell us if the build is still failing.

**Comment by johlju** [comment]
@PlagueHO another tip is that you can also close and reopen the PR to trigger the tests to run again. Then there is no need to do a dummy commit.

**Comment by PlagueHO** [comment]
@johlju - oh cool! Great tip! I'm not yet a repo maintainer on this one yet ( @zjalexander ), so can't do that myself. @ITGuyOU - are you able to do this?

**Comment by PlagueHO** [comment]
Hi @ITGuyOU - unfortunately there are some merge conflicts now (due to another PR that I merged). Are you able to fix these and I'll help get any failing tests fixed up.

**Comment by PlagueHO** [comment]
@ITGuyOU - I'm going to close this one, because I've included the fix in this PR #77

**Pull request closed without merging**
