### PR TITLE
xScheduledTask: Incorrect TaskPath handling (Fixes #45)

### LINKED ISSUE #45: xScheduledTask failed
the scheduledTask created successfully, but the verify failed.

here my scheduleTask:

xScheduledTask Task_ddd_sync {
    ActionExecutable = "C:\Program Files (x86)\Robocopy\ddd_sync.cmd"
    RepeatInterval = 60
    ScheduleType = "Minutes"
    TaskName = "ddd-sync"
    DependsOn = '[xUser]TachographUser'
    Ensure = "Present"
    ExecuteAsCredential = $TachographUserCred
    StartTime = "03:00"
}

### PR DESCRIPTION
**Pull request by vlariono**
If TaskPath is specified without backslashes it can be registered with Set-TargetResource but cannot be retrieved with Get-TargetResource.  Get-TargetResource always returns “Absent” and Register-ScheduledTask is called instead of Set-ScheduledTask. It brings Issue #45 @twarnick has reported. Test-TargetResource also returns $false. 

Added reassembling of TaskPath with backslashes. Get-TargetResource should always return correct values now.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/62)

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by PlagueHO** [comment]
Hi @vlariono - sorry about the long delay getting this looked at. Are you able to fix up the merge conflicts on this one and I'll get it reviewed for you? Thank you for submitting this!

**Comment by vlariono** [comment]
Hi @PlagueHO, I will check the conflicts.

**Comment by vlariono** [comment]
Hi @PlagueHO, I modified the fix to adapt it to the current state of the resource.  The conflicts should also be solved.

**Comment by PlagueHO** [comment]
Thank you very much @vlariono - really great job. Just some minor tweaks. Really appreciate your work on this.

---

Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 123 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-KpC7yaI7OmSDbPtvlOl:-KpC7yaI7OmSDbPtvlOm:b-b8kx5y) ([raw file](https://github.com/powershell/xcomputermanagement/blob/41f75e65b1b4e23e3a86ed77f8f18bcaeece1bad/README.md#L123)):*
> ```Markdown
> ### Unreleased
> - xScheduledTask
>     - Fixed incorrect TaskPath handling (Fix #45)
> ```

Not a major one but are you able to include the link to the actual issue and drop the? E.g.
`[Fix #45](https://github.com/PowerShell/xComputerManagement/issues/45)`

---

*[README.md, line 133 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-KpC7uKDOs4rsWH-X26C:-KpC7uKDOs4rsWH-X26D:bbait1d) ([raw file](https://github.com/powershell/xcomputermanagement/blob/41f75e65b1b4e23e3a86ed77f8f18bcaeece1bad/README.md#L133)):*
> ```Markdown
>   - xVirtualMemory
> 
> >>>>>>> 09d3709ed7a50e2c4bcb965c871b18cfafc52454
> ```

Can you delete this line? It is a remnant of the merge conflict.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 270 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-KpCBIG7zQGesuke-fbb:-KpCBIG7zQGesuke-fbc:b-e9h23n) ([raw file](https://github.com/powershell/xcomputermanagement/blob/41f75e65b1b4e23e3a86ed77f8f18bcaeece1bad/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L270)):*
> ```PowerShell
>     )
> 
>     # Normalize path 
> ```

This code shows up twice - any chance you could move this down into a simple function at the bottom of this PSM1 file?

E.g.
```powershell
function ConvertTo-NormalizedTaskPath
{
  [CmdletBinding()]
  param
  (
    [Parameter(Mandatory = $true)]
    [System.String]
    $TaskPath
  )

  $pathArray = ($TaskPath -split '\\').Where( {$_})
  if ($pathArray.Count -gt 0)
  {
        $TaskPath = "\$($pathArray -join '\')\"
  }
  
  return $TaskPath
}
```

This will allow you to more easily create unit tests for this code to ensure it works correctly.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1309 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-KpCE7zpIZy44iVI4Lys:-KpCE7zpIZy44iVI4Lyt:b-gficvi) ([raw file](https://github.com/powershell/xcomputermanagement/blob/41f75e65b1b4e23e3a86ed77f8f18bcaeece1bad/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1309)):*
> ```PowerShell
>     )
> 
>     # Normalize path 
> ```

See previous comment about moving this into a function.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1333 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-KpCEC9fFO6y5cS33bla:-KpCEC9fFO6y5cS33blb:b2etm6) ([raw file](https://github.com/powershell/xcomputermanagement/blob/41f75e65b1b4e23e3a86ed77f8f18bcaeece1bad/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1333)):*
> ```PowerShell
>     }
> 
>     $DesiredValues = $PSBoundParameters
> ```

Please convert to lower case first letter for variable names. E.g. `$desiredValues`

And in the next few lines...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-:-KpCEfnw2Cjlbiek5Z8R:bhatwmp)*

**Comment by vlariono** [comment]
@PlagueHO , Thank you for your comments. I've added the function and it is called three times now since current implementation of set-Targetresource also requires normalized path.  I've also added unit tests for this function.  Other things should also be fine.

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/62#-:-KpH9gmVvz6x3CAedTqy:bnfp4nl)*

**Pull request merged**
