### PR TITLE
Fix BOM, Optin to Common Tests, Fix License Year, Add VSCode Styles - Fixes 87

### LINKED ISSUE #87: Update Year in License and Module Manifest to 2017
See https://github.com/PowerShell/DscResources/issues/298

### LINKED ISSUE #88: Add .GitHub Contributing, Issue Template and Pull Request Template
Add the files:
 - .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
To this repo to improve the amount of information being collected when issues are raised and to provide a checklist for reviewers/contributors when PR's are raised.

We should use the ones from [xFailOverCluster](https://github.com/PowerShell/xFailOverCluster/tree/dev/.github).

### LINKED ISSUE #90: Remove BOM on PS1 and PSM1 files and optin to tests
Optin to these tests once BOM is fixed:
Common Tests - Validate Module Files
Common Tests - Validate Script Files

### LINKED ISSUE #91: Add standard VSCode Style Settings
There is a set of standard .vscode style settings that should be used. Add them in.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Several of the module files were using UTF8 with BOM encoding. This PR converts them to UTF8 encoding. It also opts into the common tests:
"Common Tests - Validate Module Files"
"Common Tests - Validate Script Files"

The copyright year has also been updated to 2017 in the License.md and the module manifest.

The standard GitHub templates were added and the standard VSCode style settings were included as well.

**This Pull Request (PR) fixes the following issues:**
Fixes #87 
Fixes #88 
Fixes #90
Fixes #91 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/92)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - another one for you if you have a moment! Thank you so much BTW! No rush - only work on bringing the module up to standards of the others.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 215 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/92#-KrAc_ReB3Cb7-G87WFf:-KrAc_ReB3Cb7-G87WFg:bfgwlt7) ([raw file](https://github.com/powershell/xcomputermanagement/blob/a483b66169534b759410160e77bba692b338ea14/README.md#L215)):*
> ```Markdown
>   tests.
> * Replaced examples in README.MD to links to Example files.
> * Added the VS Code PowerShell extension formatting settings that cause PowerShell.
> ```

You got a '.' at the end here, it shouldn't be there I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/92#-:-KrAd7qPcJ-PaMtcjW-g:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @johlju - good catch. Fixed. Could you sign off for me? Thanks sir!

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 215 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/92#-KrAc_ReB3Cb7-G87WFf:-KrFF8mu3Q2b1NeYFxzJ:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/a483b66169534b759410160e77bba692b338ea14/README.md#L215)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You got a '.' at the end here, it shouldn't be there I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/92#-:-KrFFB2Zj1xNPJe21hAm:b-4agm9p)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/92#-:-KrGqjalQr5oDGhkZGup:bnfp4nl)*

**Comment by PlagueHO** [comment]
I'm ignoring code coverage warning, because I've yet to work on getting code coverage to 70%. Will work on this today.

**Pull request merged**
