### PR TITLE
Issue 22: Updating scheduled task instead of Unregister/Register

### PR DESCRIPTION
**Pull request by GitBadSanta**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/138)

### CODE REVIEW

**Comment by GitBadSanta** [comment]
This has been tested on 
- Windows 10
- Windows 2012 R1
- Windows 2016

The repetition trick is unfortunately leading to an  overlapped code.

**Comment by PlagueHO** [comment]
Looking really aweseome @GitBadSanta - this is an excellent change and thank you for submitting it! Just some really minor style tweaks to meet the Style Guidelines (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md). So if you make those changes I'll get this merged ASAP!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1181 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SM98HZ2XfM__uEbdH:-L4SM98HZ2XfM__uEbdI:b-1bugu3) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1181)):*
> ```PowerShell
>         $tempScheduledTask = New-ScheduledTask @scheduledTaskArguments -ErrorAction Stop
>         
>         if ($currentValues.Ensure -eq 'Present') {
> ```

Can you move { to next line?

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1185 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SMYVjNuXx32hxjUs5:-L4SMYVjNuXx32hxjUs6:bd7hbkm) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1185)):*
> ```PowerShell
>             $tempScheduledTask = New-ScheduledTask @scheduledTaskArguments -ErrorAction Stop
> 
>             $scheduledTask = Get-ScheduledTask -TaskName $currentValues.TaskName -TaskPath $currentValues.TaskPath -ErrorAction Stop
> ```

Non-blocking issue: Can you split parameters onto each line using ` backticks? It makes it easier to review (long lines wrap). 
E.g.
```powershell
$scheduledTask = Get-ScheduledTask `
  -TaskName $currentValues.TaskName `
  -TaskPath $currentValues.TaskPath `
  -ErrorAction Stop
```

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1190 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SMD4uxKGn8emyhbGx:-L4SMD4uxKGn8emyhbGy:bj8nrqx) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1190)):*
> ```PowerShell
>             $scheduledTask.Settings = $setting
>             $scheduledTask.Principal = $principal
> ```

Can you remove blank line?

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1191 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SMFTKiLdD1i5FicSq:-L4SMFTKiLdD1i5FicSr:b-mj411c) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1191)):*
> ```PowerShell
>             $scheduledTask.Principal = $principal
> 
>         } else {
> ```

Can you move } { to own lines? See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces for more info.

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1194 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SMr-jjzANjzsmXYgg:-L4SMr-jjzANjzsmXYgh:b-j9ji68) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1194)):*
> ```PowerShell
>             $scheduledTask = $tempScheduledTask
>         }
>        
> ```

Can you remove trailing whitespace from lines? Suggest using an editor like VS Code and enabling the "files.trimTrailingWhitespace": true setting - it will then automatically correct this.

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1215 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SNQjd55qmFTiGQA_A:-L4SNQjd55qmFTiGQA_B:bj8nrqx) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1215)):*
> ```PowerShell
>             Write-Verbose -Message ($script:localizedData.UpdateScheduledTaskMessage -f $TaskName, $TaskPath)
>             $null = Set-ScheduledTask -InputObject $scheduledTask @registerArguments
>         
> ```

Can you remove blank line?

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1216 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SNQL6YK4vZE_K09PW:-L4SNQL6YK4vZE_K09PX:b-mj411c) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1216)):*
> ```PowerShell
>             $null = Set-ScheduledTask -InputObject $scheduledTask @registerArguments
>         
>         } else {
> ```

Can you move } { to own lines? See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces for more info.

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1226 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SNXLeJGtIwyHDQamJ:-L4SNXLeJGtIwyHDQamK:b2kiu8c) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1226)):*
> ```PowerShell
> 
>             Write-Verbose -Message ($script:localizedData.RegisterScheduledTaskMessage -f $TaskName, $TaskPath)
>             Write-Verbose -Message ($TaskName)
> ```

This verbose line seems unnecessary - can it be removed?

---

*[Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1229 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SNp0jyi0X2Hngm5hS:-L4SNp0k43N4UpBGFg00:b-gwpujx) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1229)):*
> ```PowerShell
>          
>             $null = Register-ScheduledTask @registerArguments
>         }       
> ```

Got some white space here to remove :grin:

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 324 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L4SO-hgt2cIQbtQv4t_:-L4SO-hgt2cIQbtQv4ta:b112jqp) ([raw file](https://github.com/powershell/xcomputermanagement/blob/1e2c6d3a17001ea465f83689019ee35cf5e983a2/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L324)):*
> ```PowerShell
>                         }
>                     }
> ```

Can blank line be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-:-L4SO5bSOz4hfhl4KD65:b-4r5ere)*

**Comment by PlagueHO** [comment]
Hi @GitBadSanta - I'm going to begin renaming this repo over to ComputerManagementDsc, but I'd like to get your change in before that happens (otherwise it'll break your PR a lot). See #119. So let me know if you're able to get the final tweaks on this one through so I can begin the rename process. Thank you :grin:

**Comment by GitBadSanta** [comment]
Hi @PlagueHO. Sorry for the delay, and thanks for the detailled review. Hopefully all should be ok now.

**Comment by PlagueHO** [comment]
@GitBadSanta - Doh! I forgot to get you to add an entry to the CHANGELOG.MD detailing the change. Are you able to add something to that? Other than that it all looks good. Sorry about taking so long too BTW!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-:-L5V0sScpdw5Y4-rOg3j:bpfk3nf)*

**Comment by PlagueHO** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r3](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-L6AlGwMtp_YYCdsEpJD:-L6AlGwNqyYHD-bAwkpm:blwl2c1) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7cf7c4b2e754a3fe8015033cd9ca533ea9cdfe10/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - xScheduledTask:
>   - Update existing Scheduled Task using SetScheduleTask instead of UnRegister/Register - See [Issue #134](https://github.com/PowerShell/xComputerManagement/issues/134).
> ```

Thanks @GitBadSanta - one problem though: This violates the 80 char markdown line length rule: https://ci.appveyor.com/project/PowerShell/xcomputermanagement/build/1.9.390.0#L2937

Could you just make this line less than 80 chars. e.g.
```
- Update existing Scheduled Task using SetScheduleTask
  instead of UnRegister/Register - See [Issue #134](https://github.com/PowerShell/xComputerManagement/issues/134).
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138)*

**Comment by PlagueHO** [comment]
@GitBadSanta - if we can get this one merged then I can start the renaming process on this module. I haven't completed it yet because I didn't want to mess with your PR.

**Comment by GitBadSanta** [comment]
@PlagueHO : hope it's ok now. 
Sorry but it seems you work during the week end, and me during the week. That's not exactly the best schedule to move on quickly.

**Comment by PlagueHO** [comment]
@GitBadSanta - no worries at all @GitBadSanta - I'm just happy for the assistance and work you're putting in!

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/138#-:-L6s0eTpzKs9GFBqfNjW:bnfp4nl)*

**Pull request merged**
