### PR TITLE
Correct Example Style to meet HQRM and Enable Example Tests - Fixes #82

### LINKED ISSUE #82: Fix Style issues in Examples
Most of the examples don't meet style guidelines. The locations also need to be moved to more easily support auto-documentation layout.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR:
- Corrects the examples so that the meet the standards required to enable the `Common Tests - Validate Example Files`.
- Opts-in to the `Common Tests - Validate Example Files` tests.
- Renames the example files to support the change over to auto documentation resource module style.
- Ensures all examples in README.MD match examples in files and none are missing.

**Note: I could instead link the examples in README.MD instead of keeping copies in there, but as these will very soon be removed anyway due to the move to auto-documentation I didn't bother, as they get automatically assembled anyway.**

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/86)

### CODE REVIEW

**Comment by johlju** [comment]
I did not style check the examples in README.md. Since you will remove them. Why not remove them now and add an Examples header instead pointing to the Examples folder?
https://github.com/PowerShell/xSQLServer#examples

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Examples/xOfflineDomainJoin/1-JoinDomainUsingODJBlob.ps1, line 17 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-KpeiOpJNZCD5pIRfiCq:-KpeiOpJNZCD5pIRfiCr:b2ohdl1) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5b1f52971e204b4cd534df3df70724e4f450141c/Examples/xOfflineDomainJoin/1-JoinDomainUsingODJBlob.ps1#L17)):*
> ```PowerShell
>     Import-DscResource -ModuleName xComputerManagement
> 
>     node $NodeName
> ```

`Node` upper 'N'

---

*[Examples/xVirtualMemory/1-SetVirtualMemory.ps1, line 21 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-Kpei6-bLfRWhUg7M2RW:-Kpei6-bLfRWhUg7M2RX:b-vq694m) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5b1f52971e204b4cd534df3df70724e4f450141c/Examples/xVirtualMemory/1-SetVirtualMemory.ps1#L21)):*
> ```PowerShell
>         xVirtualMemory pagingSettings
>         {
>             Type = "CustomSize"
> ```

Single quotes, here and the three lines below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-:-KpeiYI-vX9RwmZPzUK0:b3pvxqt)*

**Comment by PlagueHO** [comment]
Thanks for reviewing @Johlju! I've moved all the examples out of the README.MD and replaced them with links - I also moved the example links to be under the resource header they actually apply to.

While I was at it I found some spelling errors in the filenames and corrected those.

---

Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[Examples/xOfflineDomainJoin/1-JoinDomainUsingODJBlob.ps1, line 17 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-KpeiOpJNZCD5pIRfiCq:-Kpg5ywsz75Lq9ZWZFoT:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5b1f52971e204b4cd534df3df70724e4f450141c/Examples/xOfflineDomainJoin/1-JoinDomainUsingODJBlob.ps1#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`Node` upper 'N'
</blockquote></details>

Done.

---

*[Examples/xVirtualMemory/1-SetVirtualMemory.ps1, line 21 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-Kpei6-bLfRWhUg7M2RW:-Kpg6-jV7DqXOhVwxu9Y:bhknay4) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5b1f52971e204b4cd534df3df70724e4f450141c/Examples/xVirtualMemory/1-SetVirtualMemory.ps1#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single quotes, here and the three lines below.
</blockquote></details>

Done. And aligned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-:-Kpg5eljC-J7TJGRed2c:b-ylr71w)*

**Comment by johlju** [comment]
Reviewed 1 of 18 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/86#-:-Kpg9LouMjx9yXGAAAMh:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks for reviewing @johlju

**Pull request merged**
