### PR TITLE
BREAKING CHANGE: xScheduledTask Duration/Interval Fields Changed to Strings - Fixes #85

### LINKED ISSUE #85: xScheduleTask - Time Zone issues
@PlagueHO I've started converting all my cScheduledTask (totally different resource) configurations to xScheduledTask and noticed some time zone issues. The configuration is being built in Australia but the servers are in New Zealand.

I need a task to run every 15 minutes for 23 hours a day. So I used the following config.

```
RepeatInterval     = '00:15:00'
RepetitionDuration = '23:00:00'

```
However, I get the following issue.

```
Invoke-CimMethod : PowerShell DSC resource MSFT_xScheduledTask  failed to execute Set-TargetResource functionality with error message: Repetition duration 01:00:00 is less than repetition interval 02:15:00. Please set RepeatInterval to a value lower or 
equal to RepetitionDuration
```

If I do something like this...

```
RepeatInterval     = [datetime]::Today.AddMinutes(15)
RepetitionDuration = '20:00:00'
```
...then the scheduled task is set to start 12:00AM, repeat every 02:15:00 for a duration of 22:00:00.

I think one solution would be to add a property to the resource called 'UseLocalTime' this would resolve the issue without having a breaking change.

Another question is how do I set the duration to Indefinitely?

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
BREAKING CHANGE: This PR changes the parameters `RepeatInterval`, `RepetitionDuration`, `RandomDelay`, `IdleWaitTimeout`, `IdleDuration`, `ExecutionTimeLimit` and `RestartInterval` to string fields. These fields were [DateTime] fields, but this caused issues when applying MOF files that were created in a different time zone.

The code was also refactored to reduce code reuse and some HQRM changes were made. However, the resource still requires further changes to complete the HQRM conversion.

**This Pull Request (PR) fixes the following issues:**
Fixes #85

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/100)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@johlju - would you mind reviewing this one if you get a chance (no rush)? It is fairly large because I needed to refactor quite a bit of code to get this working correctly.

It does not been style guidelines yet, but I will work on that in a separate PR because I didn't want this PR to get any larger :cry: I will be working on the HQRM for each resource, one-by-one at a later date.

**Comment by johlju** [comment]
Sure I will help you review, try to get to it as soon as I can.
Will try to ignore style for this one :smile:

**Comment by johlju** [comment]
Have not reviewed the actually code yet. Will do that as soon as I have time again. :)

---

Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuESWwtNy-QgqL5mzZK:-KuESWwtNy-QgqL5mzZL:bgn9y2x) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L3)):*
> five tasks

Six tasks

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuESotOmt02ksWP5iny:-KuESotOmt02ksWP5inz:bsjhkp5) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L3)):*
> ```PowerShell
> <#
>     .EXAMPLE
>     This example creates five tasks with the following schedules that start a new powershell process
> ```


Wouldn't it be better to split these into separate example files? But that is the HQRM PR you are gonna do later? 

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuETus-RhfDAfMOU1BK:-KuETus-RhfDAfMOU1BL:bt68lp6) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L34)):*
> ```PowerShell
>             ActionWorkingPath = (Get-Location).Path
>             Enable = $true
>             RandomDelay = '01:00:00'
> ```

Non-blocking: Seems random delay is important for this example? Add text explaining that? Other parameters as well that should be explained. 
Same for other examples, different parameters that are not explained in the example.
Different PR?

---

*[Examples/xScheduledTask/2-RunPowerShellTaskEvery15Minutes.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEVKCOFJl5Z_QlVVl8:-KuEVKCOFJl5Z_QlVVl9:bnep3hf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/2-RunPowerShellTaskEvery15Minutes.ps1#L25)):*
> ```PowerShell
>           ActionExecutable   = "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe"
>           ActionArguments    = "-File `"C:\scripts\my custom script.ps1`""
>           ScheduleType       = 'Once'
> ```

Should this be once if it should run every 15 minutes?

---

*[Examples/xScheduledTask/3-RunPowerShellTaskEvery15MinutesIndefinitely.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEVQKiK2df7d71PLHN:-KuEVQKjrwD_xiTQbEEO:b-rvpyl8) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/3-RunPowerShellTaskEvery15MinutesIndefinitely.ps1#L25)):*
> ```PowerShell
>           ActionExecutable   = "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe"
>           ActionArguments    = "-File `"C:\scripts\my custom script.ps1`""
>           ScheduleType       = 'Once'
> ```

Same as previous comment. Should it be Once here?

---

*[Tests/Integration/MSFT_xScheduledTask.Config.ps1, line 197 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEWHlab82vIzuWHF4t:-KuEWHlab82vIzuWHF4u:b-o5gk7y) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Config.ps1#L197)):*
> ```PowerShell
>             DaysInterval = 2
>             RepeatInterval = '00:30:00'
>             RepetitionDuration = '10.00:00:00'
> ```

Should you have this many zeros?

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 134 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEYxWTDwWbFc71lY3C:-KuEYxWTDwWbFc71lY3D:b-3cmssr) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L134)):*
> ```PowerShell
> 
>             It 'Should return a compliant state after being applied' {
>                 (Test-DscConfiguration -ReferenceConfiguration $ConfigMof -Verbose).InDesiredState | Should be $true
> ```

Shouldn't you run Get-DscConfiguration and verify the actual value was the expected time in the timezone?

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEZXbulktFj-LWrRpA:-KuEZXbulktFj-LWrRpB:b29wevv) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L37)):*
> { }

No need for this, can be removed. Throughout.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 697 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuE_PMLYieLRAwLb6Nm:-KuE_PMLYieLRAwLb6Nn:b-umg1zs) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L697)):*
> ```PowerShell
>                 }
> 
>                 Mock -CommandName Get-ScheduledTask { return @{
> ```

Non-blocking: I think you could make this dynamic mock instead? Adding the mock to BeforeEach and setting dynamic variables for any values that need to be changed.
Seems at least this one and the one above is equal. 
Try to remove duplicate code? 

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 909 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEaBXg0neZgF3JlH7W:-KuEaBXg0neZgF3JlH7X:b-brflh9) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L909)):*
> return present

Minor (non-blocking): 
"Should return the value 'Present' for the property 'Ensure' from Get-TargetResource"

or just

"Should return the correct values from Get-TargetResource"

Or maybe something better?

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 957 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEborK-OHivEzTzZoP:-KuEborK-OHivEzTzZoQ:b-srybsb) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L957)):*
> ```PowerShell
> 
>                 It 'Should return present from the get method' {
>                     $result = Get-TargetResource @testParams
> ```

Above you did not store the returned hash table in the variable. Change above? This is more readable.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 959 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEbaPJ-RX1gfYtJfi5:-KuEbaPJ-RX1gfYtJfi6:bj8uygz) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L959)):*
> ```PowerShell
>                     $result = Get-TargetResource @testParams
>                     $result.Ensure | Should Be 'Present'
>                     $result.Ensure | Should Be 'Present'
> ```

Do you want to be extra sure here? ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuEcJbM6t30jrNM5uDN:bur6v12)*

**Comment by johlju** [comment]
Just a few comments. So far this looks okay to me.

---

Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 945 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFSsQAUCT3iGXMH_62:-KuFSsQAUCT3iGXMH_63:bale5qf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L945)):*
> ```PowerShell
>         {
>             # A repetition pattern is required so create it and attach it to the trigger object
>             Write-Verbose -Message ('Configuring trigger repetition')
> ```

Really no need for parenthesis around the strings. Throughout. 

Also, full stop ('.') after each message. Throughout.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 971 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFTVd1zYttTsLB5Q3E:-KuFTVd2EIyGB4f0F5Z5:bw6g4gc) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L971)):*
> Args

rather want `...Arguments` here. Throughout (different variables uses abbreviation of 'args').

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1484 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFRgNtuB6BiGCgddOV:-KuFRgNtuB6BiGCgddOW:b-b75owf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1484)):*
> $Timespan

Non-blocking. More of a question. Should this be `$TimespanString`? So it's clear one should not pas a variable as the type `TimeSpan`?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1522 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFRyzA4rqpnWcWTqLy:-KuFRyzA4rqpnWcWTqLz:b-jr5sh6) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1522)):*
> $Timespan

Should it be `$TimeSpan`? Upper 'S'.  
https://msdn.microsoft.com/en-us/library/system.timespan(v=vs.110).aspx

if so, then throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuFVGF8LI4aDtYrgwn2:b-78llwg)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 945 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFSsQAUCT3iGXMH_62:-KuIvgMyKcg_79xm-6bv:b8jrdf7) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L945)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Really no need for parenthesis around the strings. Throughout. 

Also, full stop ('.') after each message. Throughout.
</blockquote></details>

Done.

I'll be moving all these strings to a strings file when I apply the HQRM changes later this week.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 971 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFTVd1zYttTsLB5Q3E:-KuIvt6PW_JvZk2k30iK:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L971)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Args

rather want `...Arguments` here. Throughout (different variables uses abbreviation of 'args').
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1484 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFRgNtuB6BiGCgddOV:-KuIxiu6GVt-z7NnX-O9:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1484)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $Timespan

Non-blocking. More of a question. Should this be `$TimespanString`? So it's clear one should not pas a variable as the type `TimeSpan`?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1522 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuFRyzA4rqpnWcWTqLy:-KuIxwEvqnh8LABLoZKz:b-l0lqa0) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1522)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $Timespan

Should it be `$TimeSpan`? Upper 'S'.  
https://msdn.microsoft.com/en-us/library/system.timespan(v=vs.110).aspx

if so, then throughout.

</blockquote></details>

Corrected! Big thanks to global search+replace in VS Code :grin:

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuESWwtNy-QgqL5mzZK:-KuIyCKjsEwP5zGOZYCe:bp1lbig) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> five tasks

Six tasks
</blockquote></details>

Awesome catch! :grin:

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuESotOmt02ksWP5iny:-KuIyRD54BqJ-EmkLiZ-:b-bqbpa1) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Wouldn't it be better to split these into separate example files? But that is the HQRM PR you are gonna do later? 
</blockquote></details>

Was going to wait till HQRM, but did it now anyway.

---

*[Examples/xScheduledTask/1-CreateScheduledTasks.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuETus-RhfDAfMOU1BK:-KuIypxaOdxb92QlL-OX:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/1-CreateScheduledTasks.ps1#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: Seems random delay is important for this example? Add text explaining that? Other parameters as well that should be explained. 
Same for other examples, different parameters that are not explained in the example.
Different PR?
</blockquote></details>

Done.

---

*[Examples/xScheduledTask/2-RunPowerShellTaskEvery15Minutes.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEVKCOFJl5Z_QlVVl8:-KuIzFsNUId4bOtoS1ZC:b-3vl39x) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/2-RunPowerShellTaskEvery15Minutes.ps1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should this be once if it should run every 15 minutes?
</blockquote></details>

Yes. This is how it should be. It will start immediately and run powershell every 15 minutes for 4 days. 

---

*[Examples/xScheduledTask/3-RunPowerShellTaskEvery15MinutesIndefinitely.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEVQKiK2df7d71PLHN:-KuJ5ALkri0vVdmR-RCl:b-3vl39x) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Examples/xScheduledTask/3-RunPowerShellTaskEvery15MinutesIndefinitely.ps1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment. Should it be Once here?
</blockquote></details>

Yes. This is how it should be. It will start immediately and run powershell every 15 minutes for 4 days. 

---

*[Tests/Integration/MSFT_xScheduledTask.Config.ps1, line 197 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEWHlab82vIzuWHF4t:-KuJ5C0PI2THCFV6QVVv:byax1vo) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Config.ps1#L197)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should you have this many zeros?
</blockquote></details>

Yep. This is how you write a 10 day timespan (I wanted a test with a longer than 24 hour timespan in it - which was a limitation in the old version of this resource).

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 134 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEYxWTDwWbFc71lY3C:-KuJ83sKE1Uc26IV4b-U:bvq3ssg) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L134)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't you run Get-DscConfiguration and verify the actual value was the expected time in the timezone?
</blockquote></details>

I'll need to look into this one further. I did actually confirm the old version did fail this test (I was practicing a bit of TDD :grin: by creating a failing test first).

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEZXbulktFj-LWrRpA:-KuJ5wCJTuDgpXGCqtkE:b9ervt9) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> { }

No need for this, can be removed. Throughout.
</blockquote></details>

Fixed. I was going to clean up this file (add the named parameters etc) when I did the HQRM - it is still a bit of a mess.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 697 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuE_PMLYieLRAwLb6Nm:-KuJ62Nrmxki_6neB7QD:b30ke4g) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L697)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: I think you could make this dynamic mock instead? Adding the mock to BeforeEach and setting dynamic variables for any values that need to be changed.
Seems at least this one and the one above is equal. 
Try to remove duplicate code? 
</blockquote></details>

I'll be refactoring the tests when I do the move to HQRM - I was trying to limit the scope of the changes I was making :grin:

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 909 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEaBXg0neZgF3JlH7W:-KuJ7N0Gx2w2VmXbQ2Tb:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L909)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> return present

Minor (non-blocking): 
"Should return the value 'Present' for the property 'Ensure' from Get-TargetResource"

or just

"Should return the correct values from Get-TargetResource"

Or maybe something better?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 957 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEborK-OHivEzTzZoP:-KuJ6PdnT75scg1Q65VH:b-h67sga) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L957)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Above you did not store the returned hash table in the variable. Change above? This is more readable.
</blockquote></details>

Done. Plus I am meaning on extending these tests further to validate the out of `Get-TargetResource`. The previous version of `Get-TargetResource` actually was very broken and didn't even return anything like the MOF output (so many bad practices). It is definitely much better now, but I need to do more work on the tests before I'm 100% happy. 

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 959 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEbaPJ-RX1gfYtJfi5:-KuJ6R-4HlvvMg_KwiRQ:b9qxrxq) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L959)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Do you want to be extra sure here? ;)
</blockquote></details>

Ooops! Good catch :grin: fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100)*

**Comment by PlagueHO** [comment]
Hold off on finishing the review @johlju - I've broken something and need to fix it but have run out of time this evening.

**Comment by johlju** [comment]
Just a couple of comments left. 

---

Reviewed 13 of 14 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Examples/xScheduledTask/4-CreateScheduledTasksWeekly.ps1, line 5 at r3](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuKTrY2cafz75Pn0QJE:-KuKTrY2cafz75Pn0QJF:bsl2i71) ([raw file](https://github.com/powershell/xcomputermanagement/blob/753b77c2a69b55ace5eed820d1e2f97d472ccae4/Examples/xScheduledTask/4-CreateScheduledTasksWeekly.ps1#L5)):*
> Mon, Wed, Sat

Please use "...Monday, Wednesday and Saturday at...".

---

*[Tests/Integration/MSFT_xScheduledTask.Config.ps1, line 197 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEWHlab82vIzuWHF4t:-KuKUWanGljPAcvSffUE:b1jzvis) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Config.ps1#L197)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Yep. This is how you write a 10 day timespan (I wanted a test with a longer than 24 hour timespan in it - which was a limitation in the old version of this resource).
</blockquote></details>

Ah, didn't realize it was days :) All good. 

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 134 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEYxWTDwWbFc71lY3C:-KuKUeVpysTibEczrRKm:bhjykf7) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L134)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'll need to look into this one further. I did actually confirm the old version did fail this test (I was practicing a bit of TDD :grin: by creating a failing test first).
</blockquote></details>

Do you want to do that in another PR? Create issue for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuKVO3lPd11lPs30iEr:b-kzrnma)*

**Comment by johlju** [comment]
Let me know when you are done and I will browse thru the code changes again. 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 954 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuNkNw1KeibMzjlIydr:-KuNkNw1KeibMzjlIyds:b-wh2sl1) ([raw file](https://github.com/powershell/xcomputermanagement/blob/549476dc79b562955f561b7475161b518a843cf0/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L954)):*
> trigger

Upper 'T'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuNkjTm3wsHDuwunHK-:b-a04u9c)*

**Comment by PlagueHO** [comment]
All done! Thanks @Johlju - should be ready to complete review.

---

Review status: 12 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 954 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuNkNw1KeibMzjlIydr:-KuO9KRUbp_kJiHkgnvN:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/549476dc79b562955f561b7475161b518a843cf0/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L954)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> trigger

Upper 'T'
</blockquote></details>

Done.

---

*[Examples/xScheduledTask/4-CreateScheduledTasksWeekly.ps1, line 5 at r3](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuKTrY2cafz75Pn0QJE:-KuO9OOx0wNfPNSFzKYW:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/753b77c2a69b55ace5eed820d1e2f97d472ccae4/Examples/xScheduledTask/4-CreateScheduledTasksWeekly.ps1#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Mon, Wed, Sat

Please use "...Monday, Wednesday and Saturday at...".
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 134 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-KuEYxWTDwWbFc71lY3C:-KuO9TOwTKqzXHnP_Ase:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/4b2d74dc96edce12a887a7419e15f3053f2836d6/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L134)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Do you want to do that in another PR? Create issue for it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuO9UvBFLBRIaeTq2o5:b3l1lrq)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/100#-:-KuPNddb3NDMu7RxYrSM:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO Awesome work! A big one done!

**Pull request merged**
