### PR TITLE
Fix ExecutionTimeLimit to Enable No Limit - Fixes #115

### LINKED ISSUE #115: xScheduledTask ExecutionTimeLimit = '00:00:00' sets ExecutionTimeLimit to 3 days
**Details of the scenario you tried and the problem that is occurring:**
I'm trying to set scheduled task to no time execution limit; ExecutionTimeLimit = '00:00:00'
Doing this sets the execution time limit to 3 days.

This snippet was taken after deployment.
image

**The DSC configuration that is using the resource (as detailed as possible):**
        xScheduledTask DeploymentTask
        {
            Ensure = "Present"
            Enable = $true
            TaskName = $Node.TaskName
            ActionExecutable = "exe"
            ActionArguments = "args"
            ActionWorkingPath = "path"
            ScheduleType = 'Daily'
            StartTime = [datetime]::Now.AddMinutes($Node.TaskIntervalMinutes)
            MultipleInstances = "IgnoreNew"
            ExecutionTimeLimit = '00:00:00'
            RepeatInterval = '00:15:00'
            RepetitionDuration = 'Indefinitely'
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Server 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
3.1.0.0

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR enables setting the ExecutionTimeLimit to no limit (indefinite) by setting the parameter to '00:00:00'. Note: setting ExecutionTimeLimit has to be done differently on Windows Server 2012 R2 and Windows Server 2016/Windows 10, so I've added code to handle them all.

**This Pull Request (PR) fixes the following issues:**
#115

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - if you wouldn't mind and have the time would you be able to review?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/118)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 749 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118#-L0-ya8QqDlhNMSPc9xq:-L0-ya8QqDlhNMSPc9xr:b-bfnk2l) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8b8f1ce549b6b298b205b5d42201a8e94dface1c/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L749)):*
> -Times 1

Maybe `-Exactly -Times 1`? If you only want them to happen once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118)*

**Comment by PlagueHO** [comment]
@johlju - all done! Thanks for reviewing as always!

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 749 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118#-L0-ya8QqDlhNMSPc9xq:-L03Y6_T5P5wmY40y7sz:b-kvnr2w) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8b8f1ce549b6b298b205b5d42201a8e94dface1c/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L749)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -Times 1

Maybe `-Exactly -Times 1`? If you only want them to happen once.
</blockquote></details>

I made the correction to all in the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118#-:-L03YBKz-yhKcifI3bHK:bkpqdqc)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118#-:-L048WIF-QfcBVFvz8l5:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hi @johlju - I fixed the merge conflicts. Could you sign the last file off again? Thank you!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/118#-:-L09SHy-zPIjaJt-vWub:bnfp4nl)*

**Pull request merged**
