### PR TITLE
Correct to DomainAlreadyJoinedhMessage variable name

### PR DESCRIPTION
**Pull request by PlagueHO**
Correct spelling mistake in DomainAlreadyJoinedhMessage.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/28)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 139 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28#-KEyjKi-9NX4e2dlt157:-KEyjKi-9NX4e2dlt158:1549128127) ([raw file](https://github.com/powershell/xcomputermanagement/blob/488ad02141d2daed356697b44295e73b83113f99/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L139)):*
add a comment about the change in readme

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 139 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28#-KEyjKi-9NX4e2dlt157:-KF6i9VgrX2infDjz1vb:263181534) ([raw file](https://github.com/powershell/xcomputermanagement/blob/488ad02141d2daed356697b44295e73b83113f99/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L139)):*
Should this need an additional comment as this was a change to code that hasn't yet been merged to dev (e.g. new code added by this PR)? No problem if you want me to add it though - just wasn't sure what the general rule is in this situation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 139 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28#-KEyjKi-9NX4e2dlt157:-KF7ibDyL4cXaDHM2xzu:-1481029486) ([raw file](https://github.com/powershell/xcomputermanagement/blob/488ad02141d2daed356697b44295e73b83113f99/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L139)):*
I think it's good practice.  Just a short notice that you fixed something.  We should assume people are using even the dev branches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Comment by PlagueHO** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 139 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28#-KEyjKi-9NX4e2dlt157:-KF7oL4BUs_zSmeP0UBD:-429667581) ([raw file](https://github.com/powershell/xcomputermanagement/blob/488ad02141d2daed356697b44295e73b83113f99/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L139)):*
Cool! Consider it done :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/28)*

**Pull request merged**
