### PR TITLE
Moved Common Module Resource strings to Localization File - Fixes #122

### LINKED ISSUE #122: Move all message & exception strings for CommonResourceHelper Localization File
**Details of the scenario you tried and the problem that is occurring:**
The message strings in the CommonResourceHelper module are within the module file and need to me moved to a strings file to meet HQRM.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR makes the following changes:
1. Moved all helper modules into a Modules folder (to match other resources).
2. Split the standard Common Resource Helper functions into ComputerManagementDsc.ResourceHelper.psm1 module (functions are the same across multiple resource modules in resource kit).
3. Split the common functions that are specific to xComputerManagement into a ComputerManagementDsc.Common.psm1 module.
4. Moved strings for ComputerManagementDsc.Common.psm1 into a localization strings file.
5. Added unit tests for ComputerManagementDsc.Common module.
6. Converted all resource modules to use split ComputerManagementDsc.* modules.

**This Pull Request (PR) fixes the following issues:**
- Fixes #122

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/123)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@johlju - would you mind reviewing when you get a chance? This module is nearly at HQRM (only xScheduledTask required to be updated) - so hopefully I'll be done with the cleanup and can start fixing some issues.

**Comment by johlju** [comment]
:lgtm:

Just a nitpick non-blocking comment. No need to fix it you don't feel like it. 

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/ComputerManagementDsc.Common.tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/123#-L0ZIj6bVTqlrQvn7RCr:-L0ZIj6bVTqlrQvn7RCs:b-7g9ngr) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8fb56f17750ed6295804058ca22ccf3cb614a8fd/Tests/Unit/ComputerManagementDsc.Common.tests.ps1#L1)):*
> ```PowerShell
> $script:ModuleName = 'ComputerManagementDsc.Common'
> ```

Minor: This file has 'tests' with lower-case 't'. Should be '.Tests.'. Non-blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/123#-:-L0ZJQh87tt9PglwJvEp:b9zrsrf)*

**Comment by PlagueHO** [comment]
All done @Johlju - I did the rename, so could you sign this one off again for me :grin: thanks again sir!

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/ComputerManagementDsc.Common.Tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/123#-L0ZIj6bVTqlrQvn7RCr:-L0hJww3ND3c48scRHF-:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8fb56f17750ed6295804058ca22ccf3cb614a8fd/Tests/Unit/ComputerManagementDsc.Common.Tests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: This file has 'tests' with lower-case 't'. Should be '.Tests.'. Non-blocking.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/123#-:-L0hJy0eP9zWHxUr7IEh:b-a2bwcf)*

**Comment by PlagueHO** [comment]
Thanks @Johlju!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/123#-:-L0i3BJTPIONzxWXIx15:b-cn2syp)*

**Pull request merged**
