### PR TITLE
xScheduledTask: Add support for RunLevel and LogonType - Fixes #107

### LINKED ISSUE #107: xScheduledTask - Missing Only when logged in & Run with elevated rights
Hi
If I'm not missing anything it seems that i cannot set to run the action with higher privileges and I cannot set Only when User is logged on.

This two are important for a project I work on... would be really nice to have this implemented.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Add support for RunLevel and LogonType to xScheduledTask

**This Pull Request (PR) fixes the following issues:**
 - #107 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju  - would you mind reviewing if you get a moment? Thank you sir!

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/112)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 192 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjv_6yV379CPFSG7uU:-Kyjv_6yV379CPFSG7uV:bdfi9s4) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L192)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $ActionExecutable,
> ```

If mandatory parameters are not used in the Get-TargetResource function, please add 'Not used in Get-TargetResource.` in the comment-based help.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 196 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjv70GhuF_SXMVb2B9:-Kyjv70Hg9DSi4Jtefxt:b-bmlevn) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L196)):*
> ```PowerShell
>         [Parameter()]
>         [System.String]
>         $ActionArguments,
> ```

Are all of these parameters used in Get-TargetResource? If not all non-mandatory parameters should be remove as parameters. 

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1073 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjww-yhKpiHEOZyEwu:-Kyjww-yhKpiHEOZyEwv:b9xlzv3) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1073)):*
> ```PowerShell
> 
>         # Set the LogonType if specified
>         if ([String]::IsNullOrEmpty($LogonType))
> ```

Could we move this block into the `else`-block above? It would feel more natural to set it to `'Password'` in the `If`-block and `'None'` in the `else`-block.

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjz6bDHL1pa_zboUqH:-Kyjz6bDHL1pa_zboUqI:b-3ieo2d) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L37)):*
> ```PowerShell
>             Weekly            = 'xScheduledTaskWeekly'
>             AtLogon           = 'xScheduledTaskLogon'
>             AtStartup         = 'xScheduledTaskStartup'
> ```

Should not the new configurations names in here?

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 187 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzGP77TG8KQRI9hv2:-KyjzGP77TG8KQRI9hv3:b-gt9g4p) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L187)):*
> ```PowerShell
>                 $current.DisallowHardTerminate | Should Be $true
>                 $current.RunOnlyIfIdle         | Should Be $false
>                 $current.Priority              | Should Be 9
> ```

Not checking for example `RunLevel` here?

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 448 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzhjfYCWGtfkEIFzZ:-KyjzhjfYCWGtfkEIFz_:b-4x81g8) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L448)):*
> $testParams

`$testParameters`. Throughout.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 483 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzlD4M9DNyTdLp8s2:-KyjzlD4M9DNyTdLp8s3:bsui1pf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L483)):*
> ```PowerShell
>                 It 'Should return the correct values from Get-TargetResource' {
>                     $result = Get-TargetResource @testParams
>                     $result.Ensure | Should Be 'Present'
> ```

Shouldn't it be another correct value checked here for `LogonType`?

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 533 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyk-AusjZRLwNjalwRZ:-Kyk-AusjZRLwNjalwR_:bvp9xpt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L533)):*
> ```PowerShell
>                 It 'Should return the correct values from Get-TargetResource' {
>                     $result = Get-TargetResource @testParams
>                     $result.Ensure | Should Be 'Present'
> ```

Shouldn't it be another correct value checked here for `RunLevel`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112)*

**Comment by PlagueHO** [comment]
Thanks for reviewing @Johlju - all done I think. I've raised a new issue to make the breaking change for removing the uneeded Get-TargetResource parameters.

---

Review status: 10 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 192 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjv_6yV379CPFSG7uU:-Kz7kMPrijbYNvP0dTlN:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L192)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If mandatory parameters are not used in the Get-TargetResource function, please add 'Not used in Get-TargetResource.` in the comment-based help.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 196 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjv70GhuF_SXMVb2B9:-Kz7lDV-xualuLpQtrl5:bqbv8f0) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L196)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Are all of these parameters used in Get-TargetResource? If not all non-mandatory parameters should be remove as parameters. 
</blockquote></details>

I definitely agree here, but if I remove them in this PR I'll need to mark this as a breaking change.

I've raised this in a separate issue here: https://github.com/PowerShell/xStorage/issues/128

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 1073 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjww-yhKpiHEOZyEwu:-Kz7oN03ZVsemkDGm3EB:b4todvh) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L1073)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could we move this block into the `else`-block above? It would feel more natural to set it to `'Password'` in the `If`-block and `'None'` in the `else`-block.
</blockquote></details>

Actually, I don't think this code is required at all - it can never actually be hit - so I've removed it.

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyjz6bDHL1pa_zboUqH:-Kz7opGwtxwDndqX06FB:bulfcf9) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should not the new configurations names in here?
</blockquote></details>

The new ones are the `xScheduledTaskExecuteAs` ones just below.

---

*[Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1, line 187 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzGP77TG8KQRI9hv2:-Kz7pOOrDwnVaa7xiA04:b-wonhot) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1#L187)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not checking for example `RunLevel` here?
</blockquote></details>

Oh good catch - fixed.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 448 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzhjfYCWGtfkEIFzZ:-Kz7phjmvzLLRxuXsFsK:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L448)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $testParams

`$testParameters`. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 483 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-KyjzlD4M9DNyTdLp8s2:-Kz7qVNqpJRlSsKyP7lA:boj1qgt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L483)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't it be another correct value checked here for `LogonType`?
</blockquote></details>

Good catch. Done.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 533 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-Kyk-AusjZRLwNjalwRZ:-Kz7qdWoViXOo00kDy7b:b-e1ueej) ([raw file](https://github.com/powershell/xcomputermanagement/blob/80f1c7484365800a1bca9705dbd9cf7071865d09/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L533)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't it be another correct value checked here for `RunLevel`?
</blockquote></details>

Another good one. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-:-Kz7qmAJCEaq5K69rQoJ:b-79ogcv)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-:-Kz9mv4hzmb_jS9ElGpm:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thank you @Johlju!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/112#-:-KzArKgY3LdGyAjl9O_O:b-2p37vb)*

**Pull request merged**
