### PR TITLE
xVirtualMemory: Refactor and improve unit test coverage and HQRM - Fixes #95

### LINKED ISSUE #81: Reach at least 70% Unit Test Code Coverage
To bring this module up to HQRM standards it needs to reach 70% unit test code coverage.

### LINKED ISSUE #95: xVirtualMemory: Improve Unit Test Coverage
**Details of the scenario you tried and the problem that is occurring:**
The unit test coverage of the xVirtualMemory resource is at 41.67% and has the lowest coverage in the resource module.

Bring this resource up to 80% coverage.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR refactors xVirtualMemory to:
- reduce code duplication
- improve testability (it was very difficult to unit test)
- meet HQRM standards
- increase unit test coverage to 95%
- convert exception calling to use CommonResourceHelper.psm1
- moved strings into localization file

**This Pull Request (PR) fixes the following issues:**
Fixes #95 
Fixes #81

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@Johlju - sorry about the size of this PR, but once I took a look at the existing code and unit tests, I found it wasn't going to be easy to get decent coverage without refactoring. The same with HQRM - the resource needed a lot of work to get it into decent shape.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/96)

### CODE REVIEW

**Comment by johlju** [comment]
I have some problems over at xSQLServer that I need to focus on. But will get to this as soon as those bugs are squashed.

**Comment by PlagueHO** [comment]
Absolutely no problem or rush @johlju - just whenever! I'm planning another PR against this repo to fix #85 so that one would take precedence in getting reviewed over this one.

**Comment by johlju** [comment]
Awesome work as usual. Just minor things.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 45 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsEyNLE2YovESPOMykR:-KsEyNLFqlL65tHKQxlR:bo2dgxw) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L45)):*
> [bool]

Change to `[System.Boolean]`?

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 50 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsEyo9_CSm_Msg-8C3A:-KsEyo9_CSm_Msg-8C3B:b-l20c1w) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L50)):*
> ```PowerShell
>     {
>         $returnValue.Type = 'AutoManagePagingFile'
>         return $returnValue
> ```

Maybe use `else` instead of returning here, and in another location, and only return at the end? But good as is too. Non-blocking.

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 385 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF-33LxWxz80BaQ1xG:-KsF-33LxWxz80BaQ1xH:b-u60efa) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L385)):*
> ```PowerShell
> }
> 
> function Set-PageFileSetting
> ```

Missed comment-based help here.

---

*[DSCResources/MSFT_xVirtualMemory/en-US/MSFT_xVirtualMemory.strings.psd1, line 7 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF-nm3iprzWKiQ7eOT:-KsF-nm3iprzWKiQ7eOU:b-9vpp7w) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/en-US/MSFT_xVirtualMemory.strings.psd1#L7)):*
> Specifting

This was a new word for me ;)

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 197 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF0l6EAv-5ppIp8EQl:-KsF0l6EAv-5ppIp8EQm:b-dwcp79) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L197)):*
> ```PowerShell
>                     -Verifiable
> 
>                 It 'Should not return a valid type and drive letter' {
> ```

"Should not..." seems wrong here, it does return something.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 237 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1AaqlzjY5QUHQd-i:-KsF1AaqlzjY5QUHQd-j:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L237)):*
> ```PowerShell
>                     -Verifiable
> 
>                 It 'Should not return a valid type and drive letter' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 351 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1LecwIMK2SgpjZbj:-KsF1LecwIMK2SgpjZbk:bsawl4z) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L351)):*
> ```PowerShell
>                         -Verifiable
> 
>                     It 'Should return false' {
> ```

Wrong text here.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 428 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1Rz7ASjW6r1SyXrZ:-KsF1Rz7ASjW6r1SyXr_:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L428)):*
> ```PowerShell
>                         -Verifiable
> 
>                     It 'Should return false' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 504 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1WMpQKdeaMaO2YMi:-KsF1WMpQKdeaMaO2YMj:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L504)):*
> ```PowerShell
>                             -Verifiable
> 
>                         It 'Should return false' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 576 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1ZxsUFvoYQ40_gek:-KsF1ZxsUFvoYQ40_gel:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L576)):*
> ```PowerShell
>                         -Verifiable
> 
>                     It 'Should return false' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 639 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1eyxMjH6m_vmPwV0:-KsF1eyxMjH6m_vmPwV1:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L639)):*
> ```PowerShell
>                             -CommandName Remove-CimInstance
> 
>                         It 'Should return false' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 696 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1jpOCZKy4KxcUfkX:-KsF1jpOCZKy4KxcUfkY:buo9nmt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L696)):*
> ```PowerShell
>                         -Verifiable
> 
>                     It 'Should return false' {
> ```

Same here

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 734 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1o1LL1WCj0FD3Aap:-KsF1o1LL1WCj0FD3Aaq:b-nt97d4) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L734)):*
> With

When?

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 764 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1sxPInnLVQZGYmwO:-KsF1sxPInnLVQZGYmwP:b-nt97d4) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L764)):*
> With

When?

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1133 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2_Hqcu33wALCdBhx:-KsF2_Hqcu33wALCdBhy:bagu9hi) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1133)):*
> ```PowerShell
>                         -Verifiable
> 
>                     It 'Should not return the expected object' {
> ```

Add a test when it do return the correct object?

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1141 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2Jzubg12MR4ndNZy:-KsF2Jzubg12MR4ndNZz:b6300zl) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1141)):*
> ```PowerShell
> 
>                     It 'Should call the correct mocks' {
>                         Assert-VerifiableMocks
> ```

Do you need this? Throughout

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1206 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2sFEcLIzASWaehBB:-KsF2sFEcLIzASWaehBC:ba1v4rf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1206)):*
> throw exception

unsure, but maybe "throw an exception"? Throughout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-:-KsF33KIAma8EATtPxmM:b-aj4mf7)*

**Comment by PlagueHO** [comment]
All fixed I think! Great review, thanks @Johlju

---

Review status: 1 of 4 files reviewed at latest revision, 17 unresolved discussions.

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 45 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsEyNLE2YovESPOMykR:-KsNcP5LqbRyivhd8YOt:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> [bool]

Change to `[System.Boolean]`?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 50 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsEyo9_CSm_Msg-8C3A:-KsNccRdtkvI3FXWbyxt:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L50)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe use `else` instead of returning here, and in another location, and only return at the end? But good as is too. Non-blocking.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1, line 385 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF-33LxWxz80BaQ1xG:-KsNdpxj8LQx9DLCOQ7u:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1#L385)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missed comment-based help here.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xVirtualMemory/en-US/MSFT_xVirtualMemory.strings.psd1, line 7 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF-nm3iprzWKiQ7eOT:-KsNeLfOKsQrzFKHQapH:br2xauz) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/DSCResources/MSFT_xVirtualMemory/en-US/MSFT_xVirtualMemory.strings.psd1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Specifting

This was a new word for me ;)
</blockquote></details>

Oops - good catch - not really sure how I ended up with that! 

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 197 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF0l6EAv-5ppIp8EQl:-KsNedNUL9--N1ihcqF1:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L197)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

"Should not..." seems wrong here, it does return something.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 237 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1AaqlzjY5QUHQd-i:-KsNelJX9s8l26z_cgcj:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L237)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 351 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1LecwIMK2SgpjZbj:-KsNf2uMUOzeLJdKYUEu:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L351)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Wrong text here.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 428 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1Rz7ASjW6r1SyXrZ:-KsNfItSYJISkN7_CQbB:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 504 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1WMpQKdeaMaO2YMi:-KsNgeutgc_jDyHL7VVk:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L504)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 576 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1ZxsUFvoYQ40_gek:-KsNgfFQSQe0YU6Z1Pua:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L576)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 639 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1eyxMjH6m_vmPwV0:-KsNggGcSCOaUihxiN2e:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L639)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 696 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1jpOCZKy4KxcUfkX:-KsNggzqfOLbT9znsHXn:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L696)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 734 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1o1LL1WCj0FD3Aap:-KsNghjcKpAh96NOJfk4:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L734)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> With

When?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 764 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF1sxPInnLVQZGYmwO:-KsNgiRQuHWwGQj_ARIo:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L764)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> With

When?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1133 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2_Hqcu33wALCdBhx:-KsNgx9Kk0xdwgN40JS1:byh5sii) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1133)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Add a test when it do return the correct object?
</blockquote></details>

Oops. Is actually testing for the correct object.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1141 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2Jzubg12MR4ndNZy:-KsNikMFkWgNmyN2obhy:b-wxuzv6) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1141)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Do you need this? Throughout
</blockquote></details>

No not needed - removed throughout.

---

*[Tests/Unit/MSFT_xVirtualMemory.Tests.ps1, line 1206 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-KsF2sFEcLIzASWaehBB:-KsNjMllBqM48uFbcTHZ:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/f7688b5964bed659f2b8f9dd80d93f44f2846d81/Tests/Unit/MSFT_xVirtualMemory.Tests.ps1#L1206)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> throw exception

unsure, but maybe "throw an exception"? Throughout
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-:-KsNjStZu8yQInBGXN1Y:b-mxxsje)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/96#-:-KsPQlBdxop_jErkmd7g:bnfp4nl)*

**Pull request merged**
