### PR TITLE
Added SystemLocale to xComputer 

### PR DESCRIPTION
**Pull request by lfshr**
Recreated Pull Request.

Creating a pull request to add SystemLocale option in xComputer. I understand that there is another Resource (SystemLocale in SystemLocaleDsc Module), but I think the Locale setting makes more sense in the xComputer resource.

I couldn't find a friendly way of implementing intellisense to help with the locales, so I hard-coded them into the schema.mof. I'm not overly attached to the barbaric approach.

Liam

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/49)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@PlagueHO You should take a look at this

**Comment by PlagueHO** [comment]
Hi @TheFish92 - thanks for submitting this. Thanks for the tag @kwirkykat .

@TheFish92 - it might be a good idea to raise an issue first for this and get some feedback from the community. If including this function in xComputerManagement makes more sense then we should move this function in here and deprecate SystemLocaleDsc, rather than maintaining two methods of setting it.

Would you be able to open an issue for this change?

**Comment by TheFish92** [comment]
No problem at all. Issue is raised. #50

**Comment by BerheAbrha** [comment]
:shipit:

**Comment by kwirkykat** [comment]
@PlagueHO This PR is on hold until you sign off

**Comment by PlagueHO** [comment]
@kwirkykat  - I think @LiamFisher92 was going to update xComputerManagement to HQRM before he merges the System Locale functionality in to this resource (I may have misunderstood though).

I don't think this PR should go in as is. The underlying functionality is great and I have no problem with it (except I still think the hard coded ValidateSet() is not right). I do think we need to get this resource to HQRM first and then add the System Locale setting in at that point as per @mgreenegit 's suggestion.

I'm still up for helping @LiamFisher92 to get this resource to HQRM and will have a bit more time free heading into the end of the year.

**Comment by LiamFisher92** [comment]
@PlagueHO As I said, I'm not overly attached to the ValidateSet. It does however raise an interesting feature request for MOF schema's, which is the ability to dynamically inject valid values at runtime. Having the list of possible locales appear in ISE is nice!

I've been crazy busy lately, and haven't had much free time. The only work I've been able to do it small stuff that is directly affecting my actual work. So I think us two chipping away at it throughout Christmas and new year is a good shout! 😄

**Comment by PlagueHO** [comment]
I'm going to close this one because @ld0614's LanguageDsc module is going to replace SystemLocaleDsc and be incorporated into this resource module (once xComputerManagement -> ComputerManagementDsc). See this issue https://github.com/PowerShell/DscResources/issues/288

**Pull request closed without merging**
