### PR TITLE
xScheduledTask: Move strings to localization file and HQRM - fixes #125

### LINKED ISSUE #121: xScheduleTask: Incorrect Message shown when Trigger Type unknown
**Details of the scenario you tried and the problem that is occurring:**
Unknown Trigger type message does not show trigger type. See issue #74.

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

### LINKED ISSUE #125: Convert xScheduledTask to HQRM and move strings to Localization File
Work on issues:

- #94 
- #80

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Convert xScheduledTask to HQRM and move strings to Localization File. Also correct message produced when existing scheduled task trigger type is not recognized.

**This Pull Request (PR) fixes the following issues:**
- Fixes #125
- Fixes #121

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - this is the last HQRM change required to this module. Would you mind reviewing if you get a chance? I can then get onto the rename and starting work on adding features again.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/126)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1, line 9 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/126#-L12U0hMGmfBdW_B9-zC:-L12U0hMGmfBdW_B9-zD:b-r79831) ([raw file](https://github.com/powershell/xcomputermanagement/blob/eb6d8a6d9fb01eec9a244f5625760b965d5b3dbf/DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1#L9)):*
> 0

Minor, no-blocking: Maybe change to '...zero (0)...'? This and the one below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/126#-:-L12UMdk7pnVxNdCFX7X:bnfp4nl)*

**Comment by PlagueHO** [comment]
All done - could you sign off for me? :grin: Thanks again @johlju!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1, line 9 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/126#-L12U0hMGmfBdW_B9-zC:-L13pkOeStLKfz4nWSeV:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/eb6d8a6d9fb01eec9a244f5625760b965d5b3dbf/DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> 0

Minor, no-blocking: Maybe change to '...zero (0)...'? This and the one below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/126#-:-L13pm0--y3KK1gPBvtX:b-vhz1p1)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/126#-:-L13vALfNFRelSRm85kW:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks again @johlju

**Pull request merged**
