### PR TITLE
Added xScheduledTask resource

### PR DESCRIPTION
**Pull request by BrianFarnhill**
This PR includes a new resource for managing scheduled tasks. It's not something that is flexible enough for every possible scenario to do with managed tasks, but will allow the scheduling of tasks that recur every X number of minutes/hours/days, and you can control the account they execute with. 

Unit tests, examples and readme have all been updated, and all existing tests still pass.

Let me know if you need anything else with this one.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/30)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@BrianFarnhill  - I Lol'd reading your commit messages :smile:

**Comment by PlagueHO** [comment]
Sorry about all the StyleGuidelnes nags. But other than those, it looks pretty good to me.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[README.md, line 60 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk4w8R-11jqXSJ_RKR:-KGk4w8R-11jqXSJ_RKS:-1360238617) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/README.md#L60)):*
I know it is mostly pretty obvious, but it might be worth mentioning which of these parameters is required and which are optional.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 6 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6cauiROXAi3UyDQ0:-KGk6cauiROXAi3UyDQ1:208901755) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L6)):*
Are you able to change the Parameter formats to match the StyleGuidelines (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-names-should-be-separated-by-a-single-line)?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 19 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk83ICPj60l3Tr4MIR:-KGk83ICPj60l3Tr4MIS:-619879909) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L19)):*
Braces should be on the following line (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#braces-should-always-be-on-a-following-line).

This problem occurs a few more times further down.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 40 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk5vv8wzU10b9XS1bT:-KGk5vv8wzU10b9XS1bU:-496777245) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L40)):*
Any chance we can get this line below 100 chars?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 44 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6-9SzIkdVbUrTXrH:-KGk6-9SzIkdVbUrTXrI:-496777245) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L44)):*
Any chance we can get this line below 100 chars?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 47 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk600H6WIe3Hdb5e24:-KGk600H6WIe3Hdb5e25:-496777245) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L47)):*
Any chance we can get this line below 100 chars?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 71 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6o5eNCcwqSHC4at7:-KGk6o5eNCcwqSHC4at8:208901755) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L71)):*
Are you able to change the Parameter formats to match the StyleGuidelines (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-names-should-be-separated-by-a-single-line)?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 106 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6BoCTmSv994LG5IJ:-KGk6BoCTmSv994LG5IK:-496777245) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L106)):*
Any chance we can get this line below 100 chars?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 126 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk8m4XDt9vv26nAm2g:-KGk8m4XDt9vv26nAm2h:1627416777) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L126)):*
Positional parameters used - can we change that? https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#call-cmdlets-using-all-named-parameters-instead-of-positional-parameters

A few more occurrences further on.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 154 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6pMqF-RjFS87nEep:-KGk6pMqF-RjFS87nEeq:208901755) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L154)):*
Are you able to change the Parameter formats to match the StyleGuidelines (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-names-should-be-separated-by-a-single-line)?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk76bEAIIoom0-QBew:-KGk76bEAIIoom0-QBex:-496777245) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L171)):*
Any chance we can get this line below 100 chars?

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk7XlkqUp7hA4hHczx:-KGk7XlkqUp7hA4hHczy:-28090743) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L1)):*
Are you able to update this Test template header to be the latest v1.1 header (from https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)? Can you also include the version number in it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-:-KGk97i-mXAA1PYQhttD:2030214829)*

**Comment by BrianFarnhill** [comment]
@PlagueHO ready for another review mate

---

Review status: 2 of 5 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-:-KGkRwqv6uJmTi_Y_vIj:-360417424)*

**Comment by BrianFarnhill** [comment]
Review status: 2 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[README.md, line 60 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk4w8R-11jqXSJ_RKR:-KGkSOYpRktvCgoAhsUq:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/README.md#L60)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 6 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6cauiROXAi3UyDQ0:-KGkSPIpFkzdRanovrkY:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L6)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 19 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk83ICPj60l3Tr4MIR:-KGkSPzhqoMsFwJNFQAY:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L19)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 40 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk5vv8wzU10b9XS1bT:-KGkSQexh6uB78kc8viP:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L40)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 44 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6-9SzIkdVbUrTXrH:-KGkSRJsx7fR5CDjB_5h:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L44)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 47 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk600H6WIe3Hdb5e24:-KGkSS21_5kBbzBbjpl3:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L47)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 71 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6o5eNCcwqSHC4at7:-KGkSSeBQDJdkMARvYsM:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L71)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 106 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6BoCTmSv994LG5IJ:-KGkSTMjPZ3qdSKse-ib:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L106)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 126 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk8m4XDt9vv26nAm2g:-KGkSJOivuJkNExEjGFN:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L126)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 154 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk6pMqF-RjFS87nEep:-KGkSIkyLlqFGoxCRPpU:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L154)):*
Done.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk76bEAIIoom0-QBew:-KGkSM98rVtLFQrA2luc:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L171)):*
Done.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGk7XlkqUp7hA4hHczx:-KGkSN_9ePwx3WBuUPpy:-499146009) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6a8f650f4f4ff01bcac0cd2386b5e099f50fde23/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L1)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by tysonjhayes** [comment]
This all looks super awesome, can only find one small thing that's jumping out at me.  My only ask would be if it would be possible to add integration tests to this? 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 343 \[r2\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGnwVBP9Zob7y0kYMb6:-KGnwVBQQDTjtWxxCiqW:-1188475207) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8ac2d43147fb595427361b4e1361472c712ee18a/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L343)):*
You'll have to add a line break at the end of all of the files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-:-KGnwwg9hGTBNBIgHgI_:-668989139)*

**Comment by PlagueHO** [comment]
:lgtm: Nice work BTW! Was a little bit disappointed in the lack of an amusing commit message though :smile:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-:-KGonLbyz0V4UN8PPLPp:-128234002)*

**Comment by BrianFarnhill** [comment]
@PlagueHO @tysonjhayes I'm just working on a separate PR at the moment for xHostFileEntry which I'll open shortly - will then double back here to add integration tests and we can get this merged after that.

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 343 \[r2\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGnwVBP9Zob7y0kYMb6:-KGovXoNG1CygchzGcTn:-1774884499) ([raw file](https://github.com/powershell/xcomputermanagement/blob/8ac2d43147fb595427361b4e1361472c712ee18a/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L343)):*
There already is a line break here - when there isn't reviewable shows a little red icon it indicate there isn't one, it wont ever show the actual blank line though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by BrianFarnhill** [comment]
@tysonjhayes Ready for another code review now that the integration tests are sorted

**Comment by tysonjhayes** [comment]
Reviewed 1 of 3 files at r3, 3 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 5 \[r6\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGwhZLyJvfX7LRMBIQD:-KGwhZLyJvfX7LRMBIQE:825390268) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5d82b7a2149b2bb737f783fac5ca02d869e57c86/appveyor.yml#L5)):*
Could you help me understand why we're targeting WMF 5.0? Personally I like to see us target WMF 4 (selfishly that's what I have to use).

Is this so the Remove-DSCConfigurationDocument works in your tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 5 \[r6\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGwhZLyJvfX7LRMBIQD:-KGxgMOs99d7NYR8vjaA:-969796887) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5d82b7a2149b2bb737f783fac5ca02d869e57c86/appveyor.yml#L5)):*
Yea it's 100% there for the integration tests:

 * Remove-DscConfigurationDocument to ensure we have a clean slate for each test
 * Test-DscConfiguration changes in WMF5 to allow us to test against a specific MOF file as well

This makes sure we always apply configurations cleanly in the tests, and that we test against the MOF files we expect to be on the system (accounting for something going wrong generating a MOF for example and then the test firing against the previous MOF for example)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by tysonjhayes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 5 \[r6\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGwhZLyJvfX7LRMBIQD:-KH67Y_7K64saBh_9q0K:1520001810) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5d82b7a2149b2bb737f783fac5ca02d869e57c86/appveyor.yml#L5)):*
Hmm. Guess that will break anyone running integration tests on WMF 4.0.  Could we add a #Requires -Version 5.0 at the top of the integration test to try to fail out quicker for anyone on WMF4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by BrianFarnhill** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 5 \[r6\]](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30#-KGwhZLyJvfX7LRMBIQD:-KH7LfHDfnxp9nuqeypD:495453180) ([raw file](https://github.com/powershell/xcomputermanagement/blob/5d82b7a2149b2bb737f783fac5ca02d869e57c86/appveyor.yml#L5)):*
Good call - I added that to the integration tests file (as that's the only one that needs it) and it's good to go now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/30)*

**Pull request merged**
