### PR TITLE
 Convert xOfflineDomainJoin to HQRM - Fixes #103

### LINKED ISSUE #103: Convert xOfflineDomainJoin to HQRM
**Details of the scenario you tried and the problem that is occurring:**
Convert xOfflineDomainJoin to HQRM

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
 Convert xOfflineDomainJoin to HQRM

**This Pull Request (PR) fixes the following issues:**
- Fixes #103 
- Work on #94

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/104)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 14 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPgfsZDFsWQiailssz:-KwPgfsZDFsWQiailst-:b-7m2ivp) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L14)):*
> ```PowerShell
>         Joins the computer to a domain with a domain join file.
> 
>     .PARAMETER IsSingleInstance
> ```

Please add 'Not used in Get-TargetResource.'

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 17 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPggpQubs0Fuz8Hg0c:-KwPggpQubs0Fuz8Hg0d:b-7m2ivp) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L17)):*
> ```PowerShell
>         Specifies the resource is a single instance, the value must be 'Yes'.
> 
>     .PARAMETER RequestFile
> ```

Please add 'Not used in Get-TargetResource.'

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1, line 61 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPh1nQP94Md_K-itrj:-KwPh1nQP94Md_K-itrk:b-2e9z8r) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1#L61)):*
> Mock -CommandName Test-Path -MockWith { return $False }

`$false` (lower 'f').
And could we do it like this? Throughout.

```
Mock -CommandName Test-Path -MockWith {
    return $false
}
```

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1, line 81 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPhHrywEZANIzZ6b1N:-KwPhHrywEZANIzZ6b1O:b-d52iwt) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1#L81)):*
> $True

`$true`. lower-case 't'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104)*

**Comment by PlagueHO** [comment]
Thanks @Johlju - again I really appreciate your help and fantastic reviews! Should be good to go now. I did correct some additional style things that you'd pointed out in other reviews.

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 14 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPgfsZDFsWQiailssz:-KwsOlmyz7qDcPoUheXv:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add 'Not used in Get-TargetResource.'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1, line 17 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPggpQubs0Fuz8Hg0c:-KwsOlWuI12htmybOW9W:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add 'Not used in Get-TargetResource.'
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1, line 61 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPh1nQP94Md_K-itrj:-KwsOSWdx-dh30sh5kVd:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Mock -CommandName Test-Path -MockWith { return $False }

`$false` (lower 'f').
And could we do it like this? Throughout.

```
Mock -CommandName Test-Path -MockWith {
    return $false
}
```
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1, line 81 at r2](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwPhHrywEZANIzZ6b1N:-KwsOTehrXYAgdPvbDVP:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/7347d06e0b56931d6eda635f8963a125c38a8490/Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $True

`$true`. lower-case 't'.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-:-KwsOnV4O2taUiucul2g:b-8d9hu)*

**Comment by johlju** [comment]
:lgtm:

No worries. Happy to help as always! :smile: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwuQ67HEmqCojWqhacU:-KwuQ67IDzMdqzQg1Ga5:b-pnhtu7) ([raw file](https://github.com/powershell/xcomputermanagement/blob/23fe2af91c248cb4fc5370aa2617d7ca7f4df2f5/Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1#L1)):*
> ```PowerShell
> $script:DSCModuleName = 'xComputerManagement'
> ```

Filename has lower case 't' on 'Tests. You want to fix? Non-blocking. Acknowledge if you want to leave as-is :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-:-KwuQUOx8jNHqWEGXw1B:btchx0z)*

**Comment by PlagueHO** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xOfflineDomainJoin.Tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-KwuQ67HEmqCojWqhacU:-KwvVP8SY-Q8vLJJgrjU:b-896fix) ([raw file](https://github.com/powershell/xcomputermanagement/blob/23fe2af91c248cb4fc5370aa2617d7ca7f4df2f5/Tests/Unit/MSFT_xOfflineDomainJoin.Tests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename has lower case 't' on 'Tests. You want to fix? Non-blocking. Acknowledge if you want to leave as-is :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104)*

**Comment by PlagueHO** [comment]
@Johlju - looks like this still needs a final sign off from you! Thanks again for all your help!

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-:-KwvVyeei7uMSsZDlMLx:bp97lwx)*

**Comment by johlju** [comment]
:lgtm:

The e-mail for this was far down in my inbox - finally got there :smile: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/104#-:-KxJ6u6YtOUhUwr6QiVC:bh550aj)*

**Comment by PlagueHO** [comment]
Awesome! Thanks @johlju !

**Pull request merged**
