### PR TITLE
Added dependency information for xScheduledTask to README.MD - Fixes #108

### LINKED ISSUE #108: xScheduledTask doesn't work on Windows Server 2008R2
I'm creating a DSC configuration with http pull server that will create certain scheduled tasks on both 2012R2 and 2008R2 servers.
If target node is Windows Server 2008R2 the configuration cannot be applied.
```PowerShell
PS C:\Windows\system32> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.36392
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Here are errors I see when run Update-DscConfiguration -Wait -Verbose

```PowerShell
PS C:\Windows\system32> Update-DscConfiguration -Wait -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SKS06SP001 with user sid
S-1-5-21-2727014839-3263237905-4095819900-36884.
WARNING: LCM state is changed by non-DSC operations. If you wish to change the state of LCM, please use
Remove-DscConfigurationDocument cmdlet.
VERBOSE: [SKS06SP001]:                            [] Executing Get-Action with configuration 's checksum:
F6D859ED0118E0525C85CE3F9CD5FECFF7C937A3495E75FFB28841D7C84A5E7D.
VERBOSE: [SKS06SP001]:                            [] Executing Get-Action with configuration 's checksum returned
result status: GetConfiguration.
VERBOSE: [SKS06SP001]:                            [] Checksum is different. LCM will execute GetConfiguration to pull
configuration .
VERBOSE: [SKS06SP001]:                            [] Executing GetConfiguration succeeded. Configuration  was pulled
from server.
VERBOSE: [SKS06SP001]:                            [] Applying the new configuration(s) pulled.
....
VERBOSE: [SKS06SP001]: LCM:  [ Start  Resource ]  [[xScheduledTask]Task_RestartSPtimer]
VERBOSE: [SKS06SP001]: LCM:  [ Start  Test     ]  [[xScheduledTask]Task_RestartSPtimer]
VERBOSE: [SKS06SP001]:                            [[xScheduledTask]Task_RestartSPtimer] Testing scheduled task \Restart
 SPtimer
VERBOSE: [SKS06SP001]:                            [[xScheduledTask]Task_RestartSPtimer] Retrieving existing task
(\Restart SPtimer in \Microsoft\).
The term 'Get-ScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ScheduledTask:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

VERBOSE: [SKS06SP001]:                            [[xScheduledTask]Task_RestartSPtimer] No task found. returning empty
task \Restart SPtimer with Ensure = "Absent".
VERBOSE: [SKS06SP001]:                            [[xScheduledTask]Task_RestartSPtimer] Current values retrieved
VERBOSE: [SKS06SP001]:                            [[xScheduledTask]Task_RestartSPtimer] Testing DSC parameter state.
VERBOSE: [SKS06SP001]: LCM:  [ End    Test     ]  [[xScheduledTask]Task_RestartSPtimer]  in 0.8260 seconds.
The PowerShell DSC resource '[xScheduledTask]Task_RestartSPtimer' with SourceInfo 'C:\DSCConfigs\Ebz_TestConfig.ps1::39
::9::xScheduledTask' threw one or more non-terminating errors while running the Test-TargetResource functionality. Thes
e errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details
.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
```

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR adds information about the xScheduledTask dependencies to README.MD.

**This Pull Request (PR) fixes the following issues:**
- Fixes #108

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - I know you're busy with work ATM, but when you're back could you review this one for me? It is just a minor documentation change so should be trivial! Thanks sir.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/146)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO no worries. Just tag me and I run thru them when I have some minutes over. :smile:

Looks good, but there is conflicts in the CHANGELOG.md. I will sign off once the conflict is resolved.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xcomputermanagement/146#-:-L6lS4Cg8XoKaKpEmN1Q:bx2gfel)*

**Comment by PlagueHO** [comment]
Thanks @johlju - Doh! I've fixed this now. Should be good to go. Sorry about that. I'm hoping to have a bit of DSC time this week to get some new PR's through and some old ones reviewed. But still keen to get your big DSCResource.Tests ones in (so that I can submit mine). If I see Michael Greene at the summit this week I'll see if I can get an ETA on when Katie might be available to merge them.

**Comment by johlju** [comment]
:lgtm:

Would be good if you could get a status update on that, or if Mariah could do it maybe?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/146#-:-L6m5hAjV6fjwr7bfApe:b-xtx2iz)*

**Comment by PlagueHO** [comment]
I'll see if I can catch one of the DSC people at one of tomorrows sessions for an update! Would love to see your containers testing stuff go in. Thanks for the review!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/146#-:-L6ns8FgP0AXC6QgkNPe:bvy131q)*

**Pull request merged**
