### PR TITLE
Convert Module to use Auto Document Wiki Format - Fixes #83

### LINKED ISSUE #83: Convert to use Auto-Documentation
This module should be converted to use the Auto-documentation style used by SharePointDsc, xNetworking, xStorage etc.

This enables the documentation and Wiki to be generated automatically from the MOF files, reducing the amount of work that needs to be done to keep the module up-to-date.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR converts the module over to use the auto documentation wiki format (first implemented by SharepointDsc).

**This Pull Request (PR) fixes the following issues:**
- #83

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - when you have time - no rush. I've purely focused on converting over to auto-documentation/wiki format, so I didn't change anything except what was required to do that. I've already deployed the Wiki so the links should just work.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/133)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 102 of 102 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[PSScriptAnalyzerSettings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-L2tYAIgzIxuL3cxgSiW:-L2tYAIgzIxuL3cxgSiX:bmfp1i6) ([raw file](https://github.com/powershell/xcomputermanagement/blob/d66ba5f47279b29a4993b90c3de2e08f45b0628b/PSScriptAnalyzerSettings.psd1#L1)):*
> ```PowerShell
> @{
> ```

Question: What does this file do? I haven't seen us using this before? Non-blocking.

---

*[.vscode/launch.json, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-L2tYV7gK43JVz09usTm:-L2tYV7gK43JVz09usTn:b-dg6nm2) ([raw file](https://github.com/powershell/xcomputermanagement/blob/d66ba5f47279b29a4993b90c3de2e08f45b0628b/.vscode/launch.json#L1)):*
> ```JSON
> {
> ```

It was your intention to commit this file? Non-blocking

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[PSScriptAnalyzerSettings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-L2tYAIgzIxuL3cxgSiW:-L2vR8Gd8MmNjg7cEbpp:bt79ksu) ([raw file](https://github.com/powershell/xcomputermanagement/blob/d66ba5f47279b29a4993b90c3de2e08f45b0628b/PSScriptAnalyzerSettings.psd1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Question: What does this file do? I haven't seen us using this before? Non-blocking.
</blockquote></details>

Actually, this shouldn't be here - I've removed it. It was superceeded by .MetaTestOptin.json. I actually need to remove it from xNetworking too as it isn't used.

---

*[.vscode/launch.json, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-L2tYV7gK43JVz09usTm:-L2vRCowby7ze14gLzKE:bcr060i) ([raw file](https://github.com/powershell/xcomputermanagement/blob/d66ba5f47279b29a4993b90c3de2e08f45b0628b/.vscode/launch.json#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It was your intention to commit this file? Non-blocking
</blockquote></details>

This was meant to be included :grin: It just makes it easier to run tests correctly for harness based resources from VS Code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-:-L2vVwTQ3HVq_HIfobAn:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @Johlju

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/133#-:-L2vdWYVehCd248vuc64:b6gs682)*

**Pull request merged**
