### PR TITLE
Add Startup & OnLogon for Schedule Type

### PR DESCRIPTION
**Pull request by DamianBis**
#34

I made this for my own use. can probably be incorporated without any issues. Had to parse the XML to deal with triggers as it's not possible using Get-ScheduledTask or Get-ScheduledTaskTrigger to get the information regarding the onstartup and onlogon

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/43)

### CODE REVIEW

**Comment by Indhukrishna** [comment]
@DamianBis Thanks for this fix. Can you please add some tests for this change?

**Comment by DamianBis** [comment]
I have finished doing personal tests on this and foudn it is working.

I will add in some tests later this week.

**Comment by mgreenegit** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 192 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43#-KVzg7hpKemgc9ZpRyX4:-KVzg7hqg25K0_QMOh6k:b-us4oaf) ([raw file](https://github.com/powershell/xcomputermanagement/blob/89a726806ddc33d861164df9e7b6c109ed883c88/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L192)):*
> ```PowerShell
>             }
>             
>             Context "A scheduled task with minutes based repetition exists and has the wrong settings" {
> ```

Throughout this section, please add new line before braces - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43)*

**Comment by mgreenegit** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 192 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43#-KVzg7hpKemgc9ZpRyX4:-KVzp4W2R8_Jwxa1NNhP:bmi2s1u) ([raw file](https://github.com/powershell/xcomputermanagement/blob/89a726806ddc33d861164df9e7b6c109ed883c88/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L192)):*
<details><summary><i>Previously, mgreenegit (Michael Greene) wrote…</i></summary>
> Throughout this section, please add new line before braces - https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces
</details>
Note, this does not apply to Pester scriptblocks, however

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43)*

**Comment by mgreenegit** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43)*

**Comment by kwirkykat** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 240 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43#-KWp9i8j5GlEsRljXAgl:-KWp9i8j5GlEsRljXAgm:bgaljle) ([raw file](https://github.com/powershell/xcomputermanagement/blob/89a726806ddc33d861164df9e7b6c109ed883c88/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L240)):*
> ```PowerShell
>             "Minutes" 
>             { 
>                 $repeatAt = New-TimeSpan -Minutes $RepeatInterval
> ```

What happens if $RepeatInterval is not provided?

---

*[DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1, line 413 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43#-KWobHrRHQ58yGgvw8jU:-KWobHrRHQ58yGgvw8jV:b-do2m56) ([raw file](https://github.com/powershell/xcomputermanagement/blob/89a726806ddc33d861164df9e7b6c109ed883c88/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1#L413)):*
> ```PowerShell
>             return $false 
>         }
>         if ($RepeatInterval -ne $currentValues.RepeatInterval) 
> ```

This parameter should now only get checked when it is provided.

```powershell
if ($PSBoundParameters.ContainsKey('RepeatInterval') -and $RepeatInterval -ne $currentValues.RepeatInterval)
```

---

*[Tests/Unit/MSFT_xScheduledTask.Tests.ps1, line 251 at r4](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43#-KWpBwAeLGDdJhCOoW5h:-KWpBwAeLGDdJhCOoW5i:b-jpbjz0) ([raw file](https://github.com/powershell/xcomputermanagement/blob/89a726806ddc33d861164df9e7b6c109ed883c88/Tests/Unit/MSFT_xScheduledTask.Tests.ps1#L251)):*
> ```PowerShell
>                     Test-TargetResource @testParams | Should Be $false
>                 }
>             }
> ```

Can you also add some tests for the OnLogon case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcomputermanagement/43)*

**Comment by bgelens** [comment]
Assigning abandoned label for now as there has been no response since @kwirkykat last review.
@DamianBis Can you address the comments?

**Comment by PlagueHO** [comment]
I'm going to close this PR as this feature has actually been added in another PR.

**Pull request closed without merging**
